from typing import NamedTuple, Dict, Optional, Callable, TYPE_CHECKING

from BaseClasses import Item
from BaseClasses import ItemClassification as IC

if TYPE_CHECKING:
    from . import Borderlands2World

class Borderlands2Item(Item):
    game = "Borderlands 2"

class Borderlands2ItemData(NamedTuple):
    type: str
    i_class: IC = IC.filler
    count: int = 1
    character: Optional[str] = None
    can_create: Callable[["Borderlands2World"], bool] = lambda world: True



item_data_table: Dict[str, Borderlands2ItemData] = {
    "Progressive Story Mission": Borderlands2ItemData(type="Story Mission", i_class=IC.progression, count=18),
    "The Corpse of Ug-Thak, Lord of Skags": Borderlands2ItemData(type="Claptrap Item", i_class=IC.progression_skip_balancing),
    "The Lost Staff of Mount Schuler": Borderlands2ItemData(type="Claptrap Item", i_class=IC.progression_skip_balancing),
    "The Head of The Destroyer of Worlds": Borderlands2ItemData(type="Claptrap Item", i_class=IC.progression_skip_balancing),
    "Default Dance Emote": Borderlands2ItemData(type="Claptrap Item", i_class=IC.progression_skip_balancing),
    "Brown Rock": Borderlands2ItemData(type="Claptrap Item", i_class=IC.progression_skip_balancing),
    "Common Item": Borderlands2ItemData(type="Filler"),
    "Uncommon Item": Borderlands2ItemData(type="Filler"),
    "Rare Item": Borderlands2ItemData(type="Filler"),
    "Very Rare Item": Borderlands2ItemData(type="Filler"),
    "Money": Borderlands2ItemData(type="Filler"),
    "4 Eridium": Borderlands2ItemData(type="Filler"),
    "Random Ammo": Borderlands2ItemData(type="Filler"),
    "Skill Point": Borderlands2ItemData(type="Point", i_class=IC.progression),

    # Optional Mission Unlocks # 109
    "Handsome Jack Here! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "This Town Ain't Big Enough Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bad Hair Day Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Shielded Favors Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Symbiosis Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Assassinate the Assassins Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Name Game Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rock, Paper, Genocide: Fire Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rock, Paper, Genocide: Shock Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rock, Paper, Genocide: Corrosive Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rock, Paper, Genocide: Slag Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Claptrap's Secret Stash Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Do No Harm Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Medical Mystery Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Medical Mystery: X-Com-municate Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "No Vacancy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Neither Rain Nor Sleet Nor Skags Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Too Close For Missiles Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "In Memoriam Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Cult Following: Eternal Flame Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Cult Following: False Idols Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Cult Following: Lighting the Match Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Cult Following: The Enkindling Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Positive Self Image Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Mighty Morphin' Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "You Are Cordially Invited: Party Prep Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "You Are Cordially Invited: RSVP Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "You Are Cordially Invited: Tea Party Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Out of Body Experience Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Splinter Group Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "No Hard Feelings Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Mine, All Mine Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Pretty Good Train Robbery Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Ice Man Cometh Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bandit Slaughter: Round 1 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bandit Slaughter: Round 2 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bandit Slaughter: Round 3 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bandit Slaughter: Round 4 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bandit Slaughter: Round 5 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Good, the Bad, and the Mordecai Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Slap-Happy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Stalker of Stalkers Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Best Mother's Day Ever Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Safe and Sound Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Minecart Mischief Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Arms Dealing Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Swallowed Whole Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Cold Shoulder Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Note for Self-Person Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Perfectly Peaceful Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Won't Get Fooled Again Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: Starting the War Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: First Place Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: Reach the Dead Drop Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: End of the Rainbow Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: Trailer Trashing Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: Wakey Wakey Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Clan War: Zafords vs. Hodunks Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Claptrap's Birthday Bash! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Overlooked: Medicine Man Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Overlooked: Shields Up Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Overlooked: This is Only a Test Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hidden Journals Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Torture Chairs Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Doctor's Orders Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rakkaholics Anonymous Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Poetic License Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Animal Rights Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Shoot This Guy in the Face Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Bane Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Home Movies Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hell Hath No Fury Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Written by the Victor Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Statuesque Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Rocko's Modern Strife Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Defend Slab Tower Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Contract #873 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "3:10 to Kaboom Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Breaking the Bank Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Showdown Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Animal Rescue: Medicine Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Animal Rescue: Food Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Animal Rescue: Shelter Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Truxican Standoff Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Bearer of Bad News Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Demon Hunter Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Slaughter: Round 1 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Slaughter: Round 2 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Slaughter: Round 3 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Slaughter: Round 4 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hyperion Slaughter: Round 5 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Chosen One Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Monster Mash (Part 1) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Monster Mash (Part 2) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Monster Mash (Part 3) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "A Real Boy: Clothes Make the Man Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "A Real Boy: Face Time Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "A Real Boy: Human Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Customer Service Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Kill Yourself Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "To Grandmother's House We Go Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Capture the Flags Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Lost Treasure Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "The Great Escape Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Hungry Like the Skag Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "This Just In Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Uncle Teddy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "Get to Know Jack Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),
    "You. Will. Die. (Seriously.) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression),

    # Grouped Optional Mission Unlocks # 28
    "Zafords vs. Hodunks Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Bandit Slaughter Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Hyperion Slaughter Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Dukino Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Nisha Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Scooter Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Overlook Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Rock, Paper, Genocide Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Monster Mash Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "A Real Boy Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Tiny Tea Party Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Happy Pig Motel Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Medical Mystery Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Early Hammerlock Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Early Sanctuary Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Firehawk Cult Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Dust Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Caustic Caverns Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Tundra Express Missions Unlock": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Opportunity Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Arid Nexus Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Sawtooth Cauldron Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Jack's Eridium Blight Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Tannis Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Highlands Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Mordecai Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Later Sanctuary Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),
    "Thousand Cuts Mission Unlocks": Borderlands2ItemData(type="Grouped Mission Key", i_class=IC.progression),

    # Region Keys # 36
    "Windshear Waste Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southern Shelf Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southern Shelf Bay Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Three Horns Divide Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Frostburn Canyon Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sanctuary Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sanctuary Hole Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Caustic Caverns Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Three Horns Valley Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southpaw Steam and Power Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Bloodshot Stronghold Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Bloodshot Ramparts Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Fridge Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Fink's Slaughterhouse Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Highlands Outwash Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Highlands Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Wildlife Exploitation Preserve Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Natural Selection Annex Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Opportunity Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Holy Spirits Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Thousand Cuts Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Terramorphous Peak Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Bunker Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Control Core Angel Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Tundra Express Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "End of the Line Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Dust Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Lynchwood Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Friendship Gulag Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Eridium Blight Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Ore Chasm Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sawtooth Cauldron Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Arid Nexus Boneyard Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Arid Nexus Badlands Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Hero's Pass Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Vault of the Warrior Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),

# Per Character Skills
    # Axton
    "Sentry": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Ready": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Laser Sight": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Willing": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Onslaught": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Able": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Scorched Earth": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Grenadier": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Crisis Management": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Double Up": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Impact": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Expertise": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Overload": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Metal Storm": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Steady": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Battlefront": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Longbow Turret": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Duty Calls": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Do or Die": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Ranger": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Nuke": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Healthy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Preparation": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Last Ditch Effort": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Pressure": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Forbearance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Quick Charge": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Phalanx Shield": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Resourceful": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Mag-Lock": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Grit": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Gemini": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),

    # Maya
    "Ward": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Accelerate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Suspension": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Kinetic Reflection": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Fleet": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Inertia": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Converge": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Quicken": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Sub-Sequence": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Thoughtlock": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Mind's Eye": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Sweet Release": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Restoration": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Wreck": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Elated": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Recompense": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Res": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Sustenance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Life Tap": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Scorn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Flicker": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Foresight": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Immolate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Helios": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Chain Reaction": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Backdraft": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Cloud Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Reaper": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Blight Phoenix": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Ruin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),

    # Salvador
    "Locked and Loaded": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Quick Draw": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm Your Huckleberry": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "All I Need is One": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Divergent Likeness": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Money Shot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Auto-Loader": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Lay Waste": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Down Not Out": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Keep It Piping Hot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "No Kill Like Overkill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Inconceivable": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Filled to the Brim": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "All in the Reflexes": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Last Longer": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm Ready Already": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "5 Shots or 6": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Steady as She Goes": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Yippee Ki Yay": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Double Your Fun": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Get Some": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Keep Firing...": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Hard to Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Incite": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Asbestos": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm the Juggernaut": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Ain't Got Time to Bleed": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Out of Bubblegum": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Fistful of Hurt": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Bus That Can't Slow Down": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Just Got Real": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Sexual Tyrannosaurus": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Come At Me Bro": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),

    # Zer0
    "Headsh0t": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "0ptics": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Killer": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Precisi0n": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "0ne Sh0t 0ne Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Vel0city": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "B0re": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Kill C0nfirmed": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "At 0ne with the Gun": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Critical Ascensi0n": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Fast Hands": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "C0unter Strike": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Fearless": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Ambush": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Rising Sh0t": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Unf0rseen": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Deathmark": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Innervate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Tw0 Fang": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Death Bl0ss0m": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Killing Bl0w": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Ir0n Hand": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Grim": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Be Like Water": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "F0ll0wthr0ugh": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Backstab": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Execute": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Resurgence": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Like The Wind": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Many Must Fall": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),

    # Gaige
    "Close Enough": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Cooking Up Trouble": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Fancy Mathematics": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Buck Up": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "The Better Half": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Potent as a Pony": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Upshot Robot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Unstoppable Force": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Explosive Clap": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Made of Sterner Stuff": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "20% Cooler": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Sharing is Caring": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "More Pep": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Myelin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Shock Storm": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "The Stare": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Strength of Five Gorillas": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Electrical Burn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    'Shock and "AAAGGGGHHH!"': Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Evil Enchantress": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "One Two Boom": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Wires Don't Talk": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Interspersed Outburst": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Make it Sparkle": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Smaller, Lighter, Faster": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Anarchy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Preshrunk Cyberpunk": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Robot Rampage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Blood Soaked Shields": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Annoyed Android": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Discord": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Typecast Iconoclast": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Rational Anarchist": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Death From Above": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "The Nth Degree": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "With Claws": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),

    # Krieg
    "Blood Twitch": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood-Filled Guns": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Overdrive": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Bloody Revival": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Taste of Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Bath": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Buzz Axe Bombardier": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Fuel the Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Boiling Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Trance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Nervous Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Bloodsplosion": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Empty the Rage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Pull the Pin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Feed the Meat": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Fuel the Rampage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Embrace the Pain": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Thrill of the Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Light the Fuse": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Strip the Flesh": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Redeem the Soul": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Salt the Wound": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Silence the Voices": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Release the Beast": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Burn, Baby, Burn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Fuel the Fire": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Pain is Power": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Numbed Nerves": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Elemental Elation": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Delusional Damage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Fire Fiend": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Hellfire Halitosis": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Flame Flare": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Elemental Empathy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Raving Retribution": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),

}



item_table = {name: 61 + id for id, (name, data) in enumerate(item_data_table.items()) if "Event" != data.type}
filler_items = [name for name, data in item_data_table.items() if data.type == "Filler"]
skill_items = [name for name,data in item_data_table.items() if data.type == "Skill" or data.type == "Point"]
optional_mission_items = [name for name, data in item_data_table.items() if data.type == "Optional Mission"]
grouped_optional_mission_items = [name for name, data in item_data_table.items() if data.type == "Grouped Mission Key"]
claptrap_items = [name for name, data in item_data_table.items() if data.type == "Claptrap Item"]

grouped_optional_keys = {"Zafords vs. Hodunks Missions Unlock": ('Clan War: Starting the War', 'Clan War: First Place', 'Clan War: Reach the Dead Drop', 'Clan War: End of the Rainbow', 'Clan War: Trailer Trashing', 'Clan War: Wakey Wakey', 'Clan War: Zafords vs. Hodunks'),
                         "Bandit Slaughter Missions Unlock": ('Bandit Slaughter: Round 1', 'Bandit Slaughter: Round 2', 'Bandit Slaughter: Round 3', 'Bandit Slaughter: Round 4', 'Bandit Slaughter: Round 5'),
                         "Hyperion Slaughter Missions Unlock": ('Hyperion Slaughter: Round 1', 'Hyperion Slaughter: Round 2', 'Hyperion Slaughter: Round 3', 'Hyperion Slaughter: Round 4', 'Hyperion Slaughter: Round 5'),
                         "Dukino Missions Unlock": ('Animal Rescue: Medicine', 'Animal Rescue: Food', 'Animal Rescue: Shelter', 'Demon Hunter'),
                         "Nisha Missions Unlock": ('3:10 to Kaboom', 'Breaking the Bank', 'Showdown'),
                         "Scooter Missions Unlock": ('The Cold Shoulder', 'Note for Self-Person', 'Swallowed Whole', 'Poetic License'),
                         "Overlook Missions Unlock": ('The Overlooked: Medicine Man', 'The Overlooked: Shields Up', 'The Overlooked: This is Only a Test'),
                         "Rock, Paper, Genocide Missions Unlock": ('Rock, Paper, Genocide: Fire Weapons!', 'Rock, Paper, Genocide: Shock Weapons!', 'Rock, Paper, Genocide: Corrosive Weapons!', 'Rock, Paper, Genocide: Slag Weapons!'),
                         "Monster Mash Missions Unlock": ('Monster Mash (Part 1)', 'Monster Mash (Part 2)', 'Monster Mash (Part 3)'),
                         "A Real Boy Missions Unlock": ('A Real Boy: Clothes Make the Man', 'A Real Boy: Face Time', 'A Real Boy: Human'),
                         "Tiny Tea Party Missions Unlock": ('You Are Cordially Invited: Party Prep', 'You Are Cordially Invited: RSVP', 'You Are Cordially Invited: Tea Party'),
                         "Happy Pig Motel Missions Unlock": ('No Vacancy', 'Neither Rain Nor Sleet Nor Skags', "The Ice Man Cometh"),
                         "Medical Mystery Missions Unlock": ('Do No Harm', 'Medical Mystery', 'Medical Mystery: X-Com-municate'),
                         "Early Hammerlock Missions Unlock": ('Handsome Jack Here!', "This Town Ain't Big Enough", 'Bad Hair Day', 'Shielded Favors', 'Symbiosis', 'The Name Game'),
                         "Early Sanctuary Missions Unlock": ("Assassinate the Assassins", "Claptrap's Secret Stash", "In Memoriam", 'Out of Body Experience'),
                         "Firehawk Cult Missions Unlock": ('Cult Following: Eternal Flame', 'Cult Following: False Idols', 'Cult Following: Lighting the Match', 'Cult Following: The Enkindling'),
                         "Dust Missions Unlock": ('Too Close For Missiles', 'Positive Self Image', 'Rakkaholics Anonymous'),
                         "Caustic Caverns Missions Unlock": ('Safe and Sound', 'Minecart Mischief', 'Perfectly Peaceful'),
                         "Tundra Express Missions Unlock": ("Mighty Morphin'", 'No Hard Feelings', 'Mine, All Mine', 'The Pretty Good Train Robbery'),
                         "Opportunity Mission Unlocks": ('Home Movies', 'Hell Hath No Fury', 'Written by the Victor', 'Statuesque'),
                         "Arid Nexus Mission Unlocks": ('Hungry Like the Skag', 'This Just In', 'Uncle Teddy', 'Get to Know Jack'),
                         "Sawtooth Cauldron Mission Unlocks": ('Capture the Flags', 'The Lost Treasure', 'The Great Escape', 'The Chosen One'),
                         "Jack's Eridium Blight Mission Unlocks": ('Customer Service', 'Kill Yourself', "To Grandmother's House We Go",),
                         "Tannis Mission Unlocks": ('Splinter Group', 'Hidden Journals', 'Torture Chairs', "Doctor's Orders", 'You. Will. Die. (Seriously.)'),
                         "Highlands Mission Unlocks": ('Slap-Happy', 'Stalker of Stalkers', "Best Mother's Day Ever", "Arms Dealing", 'Hyperion Contract #873'),
                         "Mordecai Mission Unlocks": ('The Good, the Bad, and the Mordecai', 'Animal Rights', 'Bearer of Bad News'),
                         "Later Sanctuary Mission Unlocks": ("Won't Get Fooled Again", "Claptrap's Birthday Bash!", "The Bane", 'Truxican Standoff'),
                         "Thousand Cuts Mission Unlocks": ('Shoot This Guy in the Face', "Rocko's Modern Strife", 'Defend Slab Tower')
                         }

optionals_grouped_key_req = {'Clan War: Starting the War': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: First Place': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: Reach the Dead Drop': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: End of the Rainbow': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: Trailer Trashing': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: Wakey Wakey': 'Zafords vs. Hodunks Missions Unlock',
                             'Clan War: Zafords vs. Hodunks': 'Zafords vs. Hodunks Missions Unlock',
                             'Bandit Slaughter: Round 1': 'Bandit Slaughter Missions Unlock',
                             'Bandit Slaughter: Round 2': 'Bandit Slaughter Missions Unlock',
                             'Bandit Slaughter: Round 3': 'Bandit Slaughter Missions Unlock',
                             'Bandit Slaughter: Round 4': 'Bandit Slaughter Missions Unlock',
                             'Bandit Slaughter: Round 5': 'Bandit Slaughter Missions Unlock',
                             'Hyperion Slaughter: Round 1': 'Hyperion Slaughter Missions Unlock',
                             'Hyperion Slaughter: Round 2': 'Hyperion Slaughter Missions Unlock',
                             'Hyperion Slaughter: Round 3': 'Hyperion Slaughter Missions Unlock',
                             'Hyperion Slaughter: Round 4': 'Hyperion Slaughter Missions Unlock',
                             'Hyperion Slaughter: Round 5': 'Hyperion Slaughter Missions Unlock',
                             'Animal Rescue: Medicine': 'Dukino Missions Unlock',
                             'Animal Rescue: Food': 'Dukino Missions Unlock',
                             'Animal Rescue: Shelter': 'Dukino Missions Unlock',
                             'Demon Hunter': 'Dukino Missions Unlock', '3:10 to Kaboom': 'Nisha Missions Unlock',
                             'Breaking the Bank': 'Nisha Missions Unlock', 'Showdown': 'Nisha Missions Unlock',
                             'The Cold Shoulder': 'Scooter Missions Unlock',
                             'Note for Self-Person': 'Scooter Missions Unlock',
                             'Swallowed Whole': 'Scooter Missions Unlock',
                             'Poetic License': 'Scooter Missions Unlock',
                             'The Overlooked: Medicine Man': 'Overlook Missions Unlock',
                             'The Overlooked: Shields Up': 'Overlook Missions Unlock',
                             'The Overlooked: This is Only a Test': 'Overlook Missions Unlock',
                             'Rock, Paper, Genocide: Fire Weapons!': 'Rock, Paper, Genocide Missions Unlock',
                             'Rock, Paper, Genocide: Shock Weapons!': 'Rock, Paper, Genocide Missions Unlock',
                             'Rock, Paper, Genocide: Corrosive Weapons!': 'Rock, Paper, Genocide Missions Unlock',
                             'Rock, Paper, Genocide: Slag Weapons!': 'Rock, Paper, Genocide Missions Unlock',
                             'Monster Mash (Part 1)': 'Monster Mash Missions Unlock',
                             'Monster Mash (Part 2)': 'Monster Mash Missions Unlock',
                             'Monster Mash (Part 3)': 'Monster Mash Missions Unlock',
                             'A Real Boy: Clothes Make the Man': 'A Real Boy Missions Unlock',
                             'A Real Boy: Face Time': 'A Real Boy Missions Unlock',
                             'A Real Boy: Human': 'A Real Boy Missions Unlock',
                             'You Are Cordially Invited: Party Prep': 'Tiny Tea Party Missions Unlock',
                             'You Are Cordially Invited: RSVP': 'Tiny Tea Party Missions Unlock',
                             'You Are Cordially Invited: Tea Party': 'Tiny Tea Party Missions Unlock',
                             'No Vacancy': 'Happy Pig Motel Missions Unlock',
                             'Neither Rain Nor Sleet Nor Skags': 'Happy Pig Motel Missions Unlock',
                             'The Ice Man Cometh': 'Happy Pig Motel Missions Unlock',
                             'Do No Harm': 'Medical Mystery Missions Unlock',
                             'Medical Mystery': 'Medical Mystery Missions Unlock',
                             'Medical Mystery: X-Com-municate': 'Medical Mystery Missions Unlock',
                             'Handsome Jack Here!': 'Early Hammerlock Missions Unlock',
                             "This Town Ain't Big Enough": 'Early Hammerlock Missions Unlock',
                             'Bad Hair Day': 'Early Hammerlock Missions Unlock',
                             'Shielded Favors': 'Early Hammerlock Missions Unlock',
                             'Symbiosis': 'Early Hammerlock Missions Unlock',
                             'The Name Game': 'Early Hammerlock Missions Unlock',
                             'Assassinate the Assassins': 'Early Sanctuary Missions Unlock',
                             "Claptrap's Secret Stash": 'Early Sanctuary Missions Unlock',
                             'In Memoriam': 'Early Sanctuary Missions Unlock',
                             'Out of Body Experience': 'Early Sanctuary Missions Unlock',
                             'Cult Following: Eternal Flame': 'Firehawk Cult Missions Unlock',
                             'Cult Following: False Idols': 'Firehawk Cult Missions Unlock',
                             'Cult Following: Lighting the Match': 'Firehawk Cult Missions Unlock',
                             'Cult Following: The Enkindling': 'Firehawk Cult Missions Unlock',
                             'Too Close For Missiles': 'Dust Missions Unlock',
                             'Positive Self Image': 'Dust Missions Unlock',
                             'Rakkaholics Anonymous': 'Dust Missions Unlock',
                             'Safe and Sound': 'Caustic Caverns Missions Unlock',
                             'Minecart Mischief': 'Caustic Caverns Missions Unlock',
                             'Perfectly Peaceful': 'Caustic Caverns Missions Unlock',
                             "Mighty Morphin'": 'Tundra Express Missions Unlock',
                             'No Hard Feelings': 'Tundra Express Missions Unlock',
                             'Mine, All Mine': 'Tundra Express Missions Unlock',
                             'The Pretty Good Train Robbery': 'Tundra Express Missions Unlock',
                             'Home Movies': 'Opportunity Mission Unlocks',
                             'Hell Hath No Fury': 'Opportunity Mission Unlocks',
                             'Written by the Victor': 'Opportunity Mission Unlocks',
                             'Statuesque': 'Opportunity Mission Unlocks',
                             'Hungry Like the Skag': 'Arid Nexus Mission Unlocks',
                             'This Just In': 'Arid Nexus Mission Unlocks',
                             'Uncle Teddy': 'Arid Nexus Mission Unlocks',
                             'Get to Know Jack': 'Arid Nexus Mission Unlocks',
                             'Capture the Flags': 'Sawtooth Cauldron Mission Unlocks',
                             'The Lost Treasure': 'Sawtooth Cauldron Mission Unlocks',
                             'The Great Escape': 'Sawtooth Cauldron Mission Unlocks',
                             'The Chosen One': 'Sawtooth Cauldron Mission Unlocks',
                             'Customer Service': "Jack's Eridium Blight Mission Unlocks",
                             'Kill Yourself': "Jack's Eridium Blight Mission Unlocks",
                             "To Grandmother's House We Go": "Jack's Eridium Blight Mission Unlocks",
                             'Splinter Group': 'Tannis Mission Unlocks',
                             'Hidden Journals': 'Tannis Mission Unlocks',
                             'Torture Chairs': 'Tannis Mission Unlocks',
                             "Doctor's Orders": 'Tannis Mission Unlocks',
                             'You. Will. Die. (Seriously.)': 'Tannis Mission Unlocks',
                             'Slap-Happy': 'Highlands Mission Unlocks',
                             'Stalker of Stalkers': 'Highlands Mission Unlocks',
                             "Best Mother's Day Ever": 'Highlands Mission Unlocks',
                             'Arms Dealing': 'Highlands Mission Unlocks',
                             'Hyperion Contract #873': 'Highlands Mission Unlocks',
                             'The Good, the Bad, and the Mordecai': 'Mordecai Mission Unlocks',
                             'Animal Rights': 'Mordecai Mission Unlocks',
                             'Bearer of Bad News': 'Mordecai Mission Unlocks',
                             "Won't Get Fooled Again": 'Later Sanctuary Mission Unlocks',
                             "Claptrap's Birthday Bash!": 'Later Sanctuary Mission Unlocks',
                             'The Bane': 'Later Sanctuary Mission Unlocks',
                             'Truxican Standoff': 'Later Sanctuary Mission Unlocks',
                             'Shoot This Guy in the Face': 'Thousand Cuts Mission Unlocks',
                             "Rocko's Modern Strife": 'Thousand Cuts Mission Unlocks',
                             'Defend Slab Tower': 'Thousand Cuts Mission Unlocks'}
