from typing import NamedTuple, Dict, Optional, Callable, TYPE_CHECKING

from BaseClasses import Item
from BaseClasses import ItemClassification as IC

if TYPE_CHECKING:
    from . import Borderlands2World

class Borderlands2Item(Item):
    game = "Borderlands 2"

class Borderlands2ItemData(NamedTuple):
    type: str
    i_class: IC = IC.filler
    count: int = 1
    character: Optional[str] = None
    can_create: Callable[["Borderlands2World"], bool] = lambda world: True



item_data_table: Dict[str, Borderlands2ItemData] = {
    "Progressive Story Mission": Borderlands2ItemData(type="Story Mission", i_class=IC.progression, count=18),
    "Common Item": Borderlands2ItemData(type="Filler"),
    "Uncommon Item": Borderlands2ItemData(type="Filler"),
    "Rare Item": Borderlands2ItemData(type="Filler"),
    "Very Rare Item": Borderlands2ItemData(type="Filler", i_class=IC.useful),
    "Money": Borderlands2ItemData(type="Filler"),
    "4 Eridium": Borderlands2ItemData(type="Filler", i_class=IC.useful),
    "Random Ammo": Borderlands2ItemData(type="Filler"),
    "Skill Point": Borderlands2ItemData(type="Point", i_class=IC.progression),

    # Optional Mission Unlocks
    "Handsome Jack Here! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "This Town Ain't Big Enough Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bad Hair Day Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Shielded Favors Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Symbiosis Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Assassinate the Assassins Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Name Game Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rock, Paper, Genocide: Fire Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rock, Paper, Genocide: Shock Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rock, Paper, Genocide: Corrosive Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rock, Paper, Genocide: Slag Weapons! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Claptrap's Secret Stash Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Do No Harm Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Medical Mystery Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Medical Mystery: X-Com-municate Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "No Vacancy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Neither Rain Nor Sleet Nor Skags Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Too Close For Missiles Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "In Memoriam Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Cult Following: Eternal Flame Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Cult Following: False Idols Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Cult Following: Lighting the Match Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Cult Following: The Enkindling Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Positive Self Image Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Mighty Morphin' Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "You Are Cordially Invited: Party Prep Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "You Are Cordially Invited: RSVP Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "You Are Cordially Invited: Tea Party Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Out of Body Experience Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Splinter Group Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "No Hard Feelings Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Mine, All Mine Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Pretty Good Train Robbery Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Ice Man Cometh Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bandit Slaughter: Round 1 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bandit Slaughter: Round 2 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bandit Slaughter: Round 3 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bandit Slaughter: Round 4 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bandit Slaughter: Round 5 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Good, the Bad, and the Mordecai Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Slap-Happy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Stalker of Stalkers Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Best Mother's Day Ever Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Safe and Sound Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Minecart Mischief Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Arms Dealing Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Swallowed Whole Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Cold Shoulder Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Note for Self-Person Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Perfectly Peaceful Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Won't Get Fooled Again Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: Starting the War Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: First Place Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: Reach the Dead Drop Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: End of the Rainbow Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: Trailer Trashing Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: Wakey Wakey Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Clan War: Zafords vs. Hodunks Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Claptrap's Birthday Bash! Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Overlooked: Medicine Man Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Overlooked: Shields Up Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Overlooked: This is Only a Test Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hidden Journals Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Torture Chairs Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Doctor's Orders Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rakkaholics Anonymous Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Poetic License Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Animal Rights Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Shoot This Guy in the Face Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Bane Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Home Movies Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hell Hath No Fury Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Written by the Victor Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Statuesque Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Rocko's Modern Strife Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Defend Slab Tower Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Contract #873 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "3:10 to Kaboom Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Breaking the Bank Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Showdown Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Animal Rescue: Medicine Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Animal Rescue: Food Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Animal Rescue: Shelter Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "BFFs Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Bearer of Bad News Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Demon Hunter Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Slaughter: Round 1 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Slaughter: Round 2 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Slaughter: Round 3 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Slaughter: Round 4 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hyperion Slaughter: Round 5 Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Chosen One Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Monster Mash (Part 1) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Monster Mash (Part 2) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Monster Mash (Part 3) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "A Real Boy: Clothes Make the Man Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "A Real Boy: Face Time Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "A Real Boy: Human Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Customer Service Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Kill Yourself Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "To Grandmother's House We Go Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Capture the Flags Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Lost Treasure Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "The Great Escape Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Hungry Like the Skag Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "This Just In Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Uncle Teddy Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "Get to Know Jack Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),
    "You. Will. Die. (Seriously.) Unlock": Borderlands2ItemData(type="Optional Mission", i_class=IC.progression_skip_balancing),

    # Region Keys
    "Windshear Waste Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southern Shelf Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southern Shelf Bay Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Three Horns Divide Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Frostburn Canyon Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sanctuary Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sanctuary Hole Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Caustic Caverns Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Three Horns Valley Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Southpaw Steam and Power Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Bloodshot Stronghold Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Bloodshot Ramparts Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Fridge Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Fink's Slaughterhouse Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Highlands Outwash Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Highlands Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Wildlike Exploitation Preserve Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Opportunity Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Holy Spirits Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Thousand Cuts Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Terramorphous Peak Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Bunker Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Control Core Angel Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Tundra Express Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "End of the Line Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "The Dust Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Lynchwood Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Friendship Gulag Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Eridium Blight Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Ore Chasm Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Sawtooth Cauldron Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Arid Nexus Boneyard Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Arid Nexus Badlands Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Hero's Pass Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),
    "Vault of the Warrior Key": Borderlands2ItemData(type="Region Key", i_class=IC.progression),

# Per Character Skills
    # Axton
    "Sentry": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Ready": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Laser Sight": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Willing": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Onslaught": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Able": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Scorched Earth": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Grenadier": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Crisis Management": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Double Up": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Impact": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Expertise": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Overload": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Metal Storm": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Steady": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Battlefront": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Longbow Turret": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Duty Calls": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Do or Die": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Ranger": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Nuke": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Healthy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Preparation": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Last Ditch Effort": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Pressure": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Forbearance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Quick Charge": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Phalanx Shield": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Resourceful": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Mag-Lock": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),
    "Grit": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Axton"),
    "Gemini": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Axton"),

    # Maya
    "Ward": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Accelerate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Suspension": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Kinetic Reflection": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Fleet": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Inertia": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Converge": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Quicken": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Sub-Sequence": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Thoughtlock": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Mind's Eye": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Sweet Release": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Restoration": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Wreck": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Elated": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Recompense": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Res": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Sustenance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Life Tap": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Scorn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Flicker": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Foresight": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Immolate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Helios": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Chain Reaction": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Backdraft": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Cloud Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),
    "Reaper": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Blight Phoenix": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Maya"),
    "Ruin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Maya"),

    # Salvador
    "Locked and Loaded": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Quick Draw": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm Your Huckleberry": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "All I Need is One": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Divergent Likeness": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Money Shot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Auto-Loader": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Lay Waste": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Down Not Out": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Keep It Piping Hot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "No Kill Like Overkill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Inconceivable": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Filled to the Brim": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "All in the Reflexes": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Last Longer": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm Ready Already": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "5 Shots or 6": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Steady as She Goes": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Yippee Ki Yay": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Double Your Fun": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Get Some": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Keep Firing...": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Hard to Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Incite": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Asbestos": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "I'm the Juggernaut": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Ain't Got Time to Bleed": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Out of Bubblegum": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Fistful of Hurt": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),
    "Bus That Can't Slow Down": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Just Got Real": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Sexual Tyrannosaurus": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Salvador"),
    "Come At Me Bro": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Salvador"),

    # Zer0
    "Headsh0t": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "0ptics": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Killer": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Precisi0n": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "0ne Sh0t 0ne Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Vel0city": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "B0re": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Kill C0nfirmed": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "At 0ne with the Gun": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Critical Ascensi0n": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Fast Hands": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "C0unter Strike": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Fearless": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Ambush": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Rising Sh0t": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Unf0rseen": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Deathmark": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Innervate": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Tw0 Fang": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Death Bl0ss0m": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Killing Bl0w": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Ir0n Hand": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Grim": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Be Like Water": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "F0ll0wthr0ugh": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Backstab": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Execute": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),
    "Resurgence": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Like The Wind": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Zero"),
    "Many Must Fall": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Zero"),

    # Gaige
    "Close Enough": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Cooking Up Trouble": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Fancy Mathematics": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Buck Up": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "The Better Half": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Potent as a Pony": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Upshot Robot": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Unstoppable Force": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Explosive Clap": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Made of Sterner Stuff": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "20% Cooler": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Sharing is Caring": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "More Pep": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Myelin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Shock Storm": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "The Stare": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Strength of Five Gorillas": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Electrical Burn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    'Shock and "AAAGGGGHHH!"': Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Evil Enchantress": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "One Two Boom": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Wires Don't Talk": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Interspersed Outburst": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Make it Sparkle": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Smaller, Lighter, Faster": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Anarchy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Preshrunk Cyberpunk": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Robot Rampage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Blood Soaked Shields": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Annoyed Android": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Discord": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Typecast Iconoclast": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "Rational Anarchist": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),
    "Death From Above": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "The Nth Degree": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Gaige"),
    "With Claws": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Gaige"),

    # Krieg
    "Blood Twitch": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood-Filled Guns": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Overdrive": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Bloody Revival": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Taste of Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Bath": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Buzz Axe Bombardier": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Fuel the Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Boiling Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Blood Trance": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Nervous Blood": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Bloodsplosion": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Empty the Rage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Pull the Pin": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Feed the Meat": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Fuel the Rampage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Embrace the Pain": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Thrill of the Kill": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Light the Fuse": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Strip the Flesh": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Redeem the Soul": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Salt the Wound": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Silence the Voices": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Release the Beast": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Burn, Baby, Burn": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Fuel the Fire": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Pain is Power": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Numbed Nerves": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Elemental Elation": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Delusional Damage": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Fire Fiend": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Hellfire Halitosis": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),
    "Flame Flare": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Elemental Empathy": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=5, character="Krieg"),
    "Raving Retribution": Borderlands2ItemData(type="Skill", i_class=IC.progression, count=1, character="Krieg"),

}



item_table = {name: 61 + id for id, (name, data) in enumerate(item_data_table.items()) if "Event" != data.type}
filler_items = [name for name, data in item_data_table.items() if data.type == "Filler"]
skill_items = [name for name,data in item_data_table.items() if data.type == "Skill" or data.type == "Point"]
optional_mission_items = [name for name, data in item_data_table.items() if data.type == "Optional Mission"]
