from typing import Dict, NamedTuple, Optional, TYPE_CHECKING

from BaseClasses import Location

if TYPE_CHECKING:
    pass

class Borderlands2Location(Location):
    game = "Borderlands 2"

class Borderlands2LocationData(NamedTuple):
    in_game_region: str
    story_region: int
    type: str
    dlc: Optional[list[str]] = None
    locked_item: Optional[str] = None

dlc_names = ["Pirate's Booty", "Campaign of Carnage", "Big Game Hunt", "Assault on Dragon Keep", "UVHM 1", "UVHM 2",
             "HH1: Bloody Harvest", "HH2: Wattle Gobbler", "HH3: Mercenary Day", "HH4: Wedding Day", "HH5: Crawmerax",
             "Fight for Sanctuary"]

location_data_table: Dict[str, Borderlands2LocationData] = {
    # Base Game Missions
    "My First Gun": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=0, type="Story Mission",),
    "Blindsided": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=1, type="Story Mission",),
    "Cleaning Up the Berg": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=2, type="Story Mission",),
    "Handsome Jack Here!": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=2, type="Optional Mission",),
    "This Town Ain't Big Enough": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=2, type="Optional Mission",),
    "Bad Hair Day": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=2, type="Optional Mission",),
    "Shielded Favors": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=2, type="Optional Mission",),
    "Symbiosis": Borderlands2LocationData(in_game_region="Southern Shelf Bay", story_region=2, type="Optional Mission",),
    "Best Minion Ever": Borderlands2LocationData(in_game_region="Southern Shelf", story_region=3, type="Story Mission",),
    "Assassinate the Assassins": Borderlands2LocationData(in_game_region="Southpaw Steam and Power", story_region=3, type="Optional Mission",),
    "The Road to Sanctuary": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Story Mission",),
    "The Name Game": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Optional Mission",),
    "Rock, Paper, Genocide: Fire Weapons!": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Optional Mission",),
    "Rock, Paper, Genocide: Shock Weapons!": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Optional Mission",),
    "Rock, Paper, Genocide: Corrosive Weapons!": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Optional Mission",),
    "Rock, Paper, Genocide: Slag Weapons!": Borderlands2LocationData(in_game_region="Sanctuary", story_region=4, type="Optional Mission",),
    "Plan B": Borderlands2LocationData(in_game_region="Sanctuary", story_region=5, type="Story Mission",),
    "Claptrap's Secret Stash": Borderlands2LocationData(in_game_region="Sanctuary", story_region=5, type="Optional Mission",),
    "Do No Harm": Borderlands2LocationData(in_game_region="Sanctuary", story_region=5, type="Optional Mission",),
    "Medical Mystery": Borderlands2LocationData(in_game_region="Three Horns Valley", story_region=5, type="Optional Mission",),
    "Medical Mystery: X-Com-municate": Borderlands2LocationData(in_game_region="Three Horns Valley", story_region=5, type="Optional Mission",),
    "No Vacancy": Borderlands2LocationData(in_game_region="Three Horns Valley", story_region=5, type="Optional Mission",),
    "Neither Rain Nor Sleet Nor Skags": Borderlands2LocationData(in_game_region="Three Horns Valley", story_region=5, type="Optional Mission",),
    "Hunting the Firehawk": Borderlands2LocationData(in_game_region="Frostburn Canyon", story_region=6, type="Story Mission",),
    "Too Close For Missiles": Borderlands2LocationData(in_game_region="The Dust", story_region=6, type="Optional Mission",),
    "In Memoriam": Borderlands2LocationData(in_game_region="Sanctuary", story_region=6, type="Optional Mission",),
    "Cult Following: Eternal Flame": Borderlands2LocationData(in_game_region="Frostburn Canyon", story_region=6, type="Optional Mission",),
    "Cult Following: False Idols": Borderlands2LocationData(in_game_region="Frostburn Canyon", story_region=6, type="Optional Mission",),
    "Cult Following: Lighting the Match": Borderlands2LocationData(in_game_region="Frostburn Canyon", story_region=6, type="Optional Mission",),
    "Cult Following: The Enkindling": Borderlands2LocationData(in_game_region="Frostburn Canyon", story_region=6, type="Optional Mission",),
    "Positive Self Image": Borderlands2LocationData(in_game_region="The Dust", story_region=6, type="Optional Mission",),
    "A Dam Fine Rescue": Borderlands2LocationData(in_game_region="Bloodshot Ramparts", story_region=7, type="Story Mission",),
    "Mighty Morphin'": Borderlands2LocationData(in_game_region="Tundra Express", story_region=7, type="Optional Mission",),
    "You Are Cordially Invited: Party Prep": Borderlands2LocationData(in_game_region="Tundra Express", story_region=7, type="Optional Mission",),
    "You Are Cordially Invited: RSVP": Borderlands2LocationData(in_game_region="Tundra Express", story_region=7, type="Optional Mission",),
    "You Are Cordially Invited: Tea Party": Borderlands2LocationData(in_game_region="Tundra Express", story_region=7, type="Optional Mission",),
    "Out of Body Experience": Borderlands2LocationData(in_game_region="Bloodshot Ramparts", story_region=7, type="Optional Mission",),
    "Splinter Group": Borderlands2LocationData(in_game_region="Bloodshot Stronghold", story_region=7, type="Optional Mission",),
    "No Hard Feelings": Borderlands2LocationData(in_game_region="Tundra Express", story_region=7, type="Optional Mission",),
    "A Train to Catch": Borderlands2LocationData(in_game_region="End of the Line", story_region=8, type="Story Mission",),
    "Mine, All Mine": Borderlands2LocationData(in_game_region="Tundra Express", story_region=8, type="Optional Mission",),
    "The Pretty Good Train Robbery": Borderlands2LocationData(in_game_region="Tundra Express", story_region=8, type="Optional Mission",),
    "The Ice Man Cometh": Borderlands2LocationData(in_game_region="Three Horns Valley", story_region=8, type="Optional Mission",),
    "Rising Action": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Story Mission",),
    "Bandit Slaughter: Round 1": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Bandit Slaughter: Round 2": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Bandit Slaughter: Round 3": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Bandit Slaughter: Round 4": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Bandit Slaughter: Round 5": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "The Good, the Bad, and the Mordecai": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Slap-Happy": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Stalker of Stalkers": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Best Mother's Day Ever": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Safe and Sound": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Minecart Mischief": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Arms Dealing": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Swallowed Whole": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "The Cold Shoulder": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Note for Self-Person": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Perfectly Peaceful": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Won't Get Fooled Again": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: Starting the War": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: First Place": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: Reach the Dead Drop": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: End of the Rainbow": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: Trailer Trashing": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: Wakey Wakey": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Clan War: Zafords vs. Hodunks": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=9, type="Optional Mission",),
    "Bright Lights, Flying City": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Story Mission",),
    "Claptrap's Birthday Bash!": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "The Overlooked: Medicine Man": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "The Overlooked: Shields Up": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "The Overlooked: This is Only a Test": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "Hidden Journals": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "Torture Chairs": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "Doctor's Orders": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=10, type="Optional Mission",),
    "Wildlife Preservation": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=11, type="Story Mission",),
    "Rakkaholics Anonymous": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=11, type="Optional Mission",),
    "Poetic License": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=11, type="Optional Mission",),
    "Animal Rights": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=11, type="Optional Mission",),
    "Shoot This Guy in the Face": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=11, type="Optional Mission",),
    "The Once and Future Slab": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Story Mission",),
    "The Bane": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Home Movies": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Hell Hath No Fury": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Written by the Victor": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Statuesque": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Rocko's Modern Strife": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Defend Slab Tower": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Hyperion Contract #873": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "3:10 to Kaboom": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Breaking the Bank": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Showdown (after both 3:10 to Kaboom and Breaking the Bank are complete)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Animal Rescue: Medicine": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Animal Rescue: Food": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "Animal Rescue: Shelter": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=12, type="Optional Mission",),
    "The Man Who Would Be Jack": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=13, type="Story Mission",),
    "Where Angels Fear to Tread": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=14, type="Story Mission",),
    "BFFs": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=14, type="Optional Mission",),
    "Bearer of Bad News": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=14, type="Optional Mission",),
    "Demon Hunter (after Animal Rescue: Shelter is complete)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=14, type="Optional Mission",),
    "Where Angels Fear to Tread (Part 2)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Story Mission",),
    "Hyperion Slaughter: Round 1": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Hyperion Slaughter: Round 2": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Hyperion Slaughter: Round 3": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Hyperion Slaughter: Round 4": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Hyperion Slaughter: Round 5": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "The Chosen One": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Monster Mash (Part 1)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Monster Mash (Part 2)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Monster Mash (Part 3)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "A Real Boy: Clothes Make the Man": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "A Real Boy: Face Time": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "A Real Boy: Human": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Customer Service": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Kill Yourself": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "To Grandmother's House We Go": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Capture the Flags": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "The Lost Treasure": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "The Great Escape": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=15, type="Optional Mission",),
    "Toil and Trouble": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=16, type="Story Mission",),
    "Hungry Like the Skag": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=16, type="Optional Mission",),
    "This Just In": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=16, type="Optional Mission",),
    "Uncle Teddy": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=16, type="Optional Mission",),
    "Get to Know Jack": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=16, type="Optional Mission",),
    "Data Mining": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=17, type="Story Mission",),
    "The Talon of God": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=18, type="Story Mission",),
    "You. Will. Die. (Seriously.)": Borderlands2LocationData(in_game_region="Windshear Waste", story_region=18, type="Optional Mission",),

    # Level Achievements
    "Level 2": Borderlands2LocationData(in_game_region="Player", story_region=2, type="Level",),
    "Level 3": Borderlands2LocationData(in_game_region="Player", story_region=2, type="Level",),
    "Level 4": Borderlands2LocationData(in_game_region="Player", story_region=3, type="Level",),
    "Level 5": Borderlands2LocationData(in_game_region="Player", story_region=3, type="Level",),
    "Level 6": Borderlands2LocationData(in_game_region="Player", story_region=4, type="Level",),
    "Level 7": Borderlands2LocationData(in_game_region="Player", story_region=4, type="Level",),
    "Level 8": Borderlands2LocationData(in_game_region="Player", story_region=5, type="Level",),
    "Level 9": Borderlands2LocationData(in_game_region="Player", story_region=6, type="Level",),
    "Level 10": Borderlands2LocationData(in_game_region="Player", story_region=7, type="Level",),
    "Level 11": Borderlands2LocationData(in_game_region="Player", story_region=7, type="Level",),
    "Level 12": Borderlands2LocationData(in_game_region="Player", story_region=7, type="Level",),
    "Level 13": Borderlands2LocationData(in_game_region="Player", story_region=8, type="Level",),
    "Level 14": Borderlands2LocationData(in_game_region="Player", story_region=9, type="Level",),
    "Level 15": Borderlands2LocationData(in_game_region="Player", story_region=10, type="Level",),
    "Level 16": Borderlands2LocationData(in_game_region="Player", story_region=10, type="Level",),
    "Level 17": Borderlands2LocationData(in_game_region="Player", story_region=11, type="Level",),
    "Level 18": Borderlands2LocationData(in_game_region="Player", story_region=11, type="Level",),
    "Level 19": Borderlands2LocationData(in_game_region="Player", story_region=11, type="Level",),
    "Level 20": Borderlands2LocationData(in_game_region="Player", story_region=12, type="Level",),
    "Level 21": Borderlands2LocationData(in_game_region="Player", story_region=13, type="Level",),
    "Level 22": Borderlands2LocationData(in_game_region="Player", story_region=13, type="Level",),
    "Level 23": Borderlands2LocationData(in_game_region="Player", story_region=14, type="Level",),
    "Level 24": Borderlands2LocationData(in_game_region="Player", story_region=14, type="Level",),
    "Level 25": Borderlands2LocationData(in_game_region="Player", story_region=14, type="Level",),
    "Level 26": Borderlands2LocationData(in_game_region="Player", story_region=14, type="Level",),
    "Level 27": Borderlands2LocationData(in_game_region="Player", story_region=15, type="Level",),
    "Level 28": Borderlands2LocationData(in_game_region="Player", story_region=16, type="Level",),
    "Level 29": Borderlands2LocationData(in_game_region="Player", story_region=17, type="Level",),
    "Level 30": Borderlands2LocationData(in_game_region="Player", story_region=18, type="Level",),
    "Level 31": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 32": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 33": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 34": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 35": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 36": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 37": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 38": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 39": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 40": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 41": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 42": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 43": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 44": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 45": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 46": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 47": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 48": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 49": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 50": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level",),
    "Level 51": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 52": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 53": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 54": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 55": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 56": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 57": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 58": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 59": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 60": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 61": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1"]),
    "Level 62": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 63": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 64": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 65": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 66": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 67": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 68": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 69": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 70": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 71": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 72": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2"]),
    "Level 73": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 74": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 75": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 76": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 77": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 78": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 79": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
    "Level 80": Borderlands2LocationData(in_game_region="Player", story_region=19, type="Level", dlc=["UVHM 1", "UVHM 2", "Fight for Sanctuary"]),
}

#location_table = {name: 7 + id for id, (name, data) in enumerate(location_data_table.keys()) if not data.type in ["Event"]}

location_table = {name: 61 + id for id, (name, data) in enumerate(location_data_table.items()) if "Event" != data.type}